<?php

namespace App\Filament\Resources\DelegteResource\Pages;

use App\Filament\Resources\DelegteResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListDelegtes extends ListRecords
{
    protected static string $resource = DelegteResource::class;

    protected function getTableQuery(): Builder
    {
        return parent::getTableQuery()->where('type','delegte'); // TODO: Change the autogenerated stub
    }

    protected function getActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }
}
