<?php

namespace App\Filament\Resources\AgentResource\Pages;

use App\Filament\Resources\AgentResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListAgents extends ListRecords
{
    protected static string $resource = AgentResource::class;


    protected function getTableQuery(): Builder
    {
        return parent::getTableQuery()->where('type','agent'); // TODO: Change the autogenerated stub
    }


    protected function getActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }
}
